//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PottMaster.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PottMaster.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikacji.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto utworzone,otwórz pocztę na tym urządzeniu i potwierdź klikając w link.
        /// </summary>
        internal static string AccountCreatedPleaseLogin {
            get {
                return ResourceManager.GetString("AccountCreatedPleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia konta.
        /// </summary>
        internal static string AccountSettings {
            get {
                return ResourceManager.GetString("AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatkowe informacje.
        /// </summary>
        internal static string AdditionalNotes {
            get {
                return ResourceManager.GetString("AdditionalNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nową pracę.
        /// </summary>
        internal static string AddNewWork {
            get {
                return ResourceManager.GetString("AddNewWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaawansowane właściwości.
        /// </summary>
        internal static string AdvancedProperties {
            get {
                return ResourceManager.GetString("AdvancedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masz już konto? Zaloguj się.
        /// </summary>
        internal static string AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analizy i raporty.
        /// </summary>
        internal static string AnalyticsAndReports {
            get {
                return ResourceManager.GetString("AnalyticsAndReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyświetl swoje miesięczne raporty Pottery Wrapped, śledź swoje postępy i analizuj trendy prac ceramicznych..
        /// </summary>
        internal static string AnalyticsDescription {
            get {
                return ResourceManager.GetString("AnalyticsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygląd wkrótce.
        /// </summary>
        internal static string AppearanceComingSoon {
            get {
                return ResourceManager.GetString("AppearanceComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Właściwości wyglądu.
        /// </summary>
        internal static string AppearanceProperties {
            get {
                return ResourceManager.GetString("AppearanceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły aplikacji.
        /// </summary>
        internal static string ApplicationDetails {
            get {
                return ResourceManager.GetString("ApplicationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notatki aplikacji.
        /// </summary>
        internal static string ApplicationNotes {
            get {
                return ResourceManager.GetString("ApplicationNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PottMaster.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artystyczna.
        /// </summary>
        internal static string Artistic {
            get {
                return ResourceManager.GetString("Artistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atmosfera.
        /// </summary>
        internal static string Atmosphere {
            get {
                return ResourceManager.GetString("Atmosphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zachowanie wkrótce.
        /// </summary>
        internal static string BehaviorComingSoon {
            get {
                return ResourceManager.GetString("BehaviorComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obie.
        /// </summary>
        internal static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do malowania.
        /// </summary>
        internal static string Brushing {
            get {
                return ResourceManager.GetString("Brushing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria.
        /// </summary>
        internal static string CategoryTitle {
            get {
                return ResourceManager.GetString("CategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień status.
        /// </summary>
        internal static string ChangeStatus {
            get {
                return ResourceManager.GetString("ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana statusu.
        /// </summary>
        internal static string ChangeStatusTitle {
            get {
                return ResourceManager.GetString("ChangeStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interakcja z gliną.
        /// </summary>
        internal static string ClayInteraction {
            get {
                return ResourceManager.GetString("ClayInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolor.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolor.
        /// </summary>
        internal static string ColorLabel {
            get {
                return ResourceManager.GetString("ColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stabilność koloru.
        /// </summary>
        internal static string ColorStability {
            get {
                return ResourceManager.GetString("ColorStability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena stożka (np. Stożek 6).
        /// </summary>
        internal static string ConeRatingExample {
            get {
                return ResourceManager.GetString("ConeRatingExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena stożka.
        /// </summary>
        internal static string ConeRatingLabel {
            get {
                return ResourceManager.GetString("ConeRatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy potwierdzasz zmianę statusu?.
        /// </summary>
        internal static string ConfirmChangeStatusMessage {
            get {
                return ResourceManager.GetString("ConfirmChangeStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz usunąć {0}?.
        /// </summary>
        internal static string ConfirmDeleteGlaze {
            get {
                return ResourceManager.GetString("ConfirmDeleteGlaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz usunąć pracę?.
        /// </summary>
        internal static string ConfirmDeleteWorkMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteWorkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź usunięcie.
        /// </summary>
        internal static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz usunąć?.
        /// </summary>
        internal static string ConfirmDeletionMessage {
            get {
                return ResourceManager.GetString("ConfirmDeletionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdzanie adresu e-mail....
        /// </summary>
        internal static string ConfirmingEmail {
            get {
                return ResourceManager.GetString("ConfirmingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrastowa.
        /// </summary>
        internal static string Contrasting {
            get {
                return ResourceManager.GetString("Contrasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz nowe konto.
        /// </summary>
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utworzono.
        /// </summary>
        internal static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz pracę.
        /// </summary>
        internal static string CreateWork {
            get {
                return ResourceManager.GetString("CreateWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tworzenie....
        /// </summary>
        internal static string CreatingWork {
            get {
                return ResourceManager.GetString("CreatingWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czułość krzywej.
        /// </summary>
        internal static string CurveSensitivity {
            get {
                return ResourceManager.GetString("CurveSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń glazurę.
        /// </summary>
        internal static string DeleteGlaze {
            get {
                return ResourceManager.GetString("DeleteGlaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuwanie.
        /// </summary>
        internal static string DeleteWorkTitle {
            get {
                return ResourceManager.GetString("DeleteWorkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suszenie zakończone.
        /// </summary>
        internal static string DryingCompleted {
            get {
                return ResourceManager.GetString("DryingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakonczono: {0:d\d\ h\h\ m\m}.
        /// </summary>
        internal static string DryingCompletedAtFormat {
            get {
                return ResourceManager.GetString("DryingCompletedAtFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suszenie zakończone!.
        /// </summary>
        internal static string DryingCompleteInfo {
            get {
                return ResourceManager.GetString("DryingCompleteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praca {0} wyschła i jest gotowa na następny etap.
        /// </summary>
        internal static string DryingCompleteMessage {
            get {
                return ResourceManager.GetString("DryingCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dni.
        /// </summary>
        internal static string DryingDays {
            get {
                return ResourceManager.GetString("DryingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpoczęto: {0:d\d\ h\h\ m\m}.
        /// </summary>
        internal static string DryingStartedFormat {
            get {
                return ResourceManager.GetString("DryingStartedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas suszenia.
        /// </summary>
        internal static string DryingTime {
            get {
                return ResourceManager.GetString("DryingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mieszanka sucha.
        /// </summary>
        internal static string DryMix {
            get {
                return ResourceManager.GetString("DryMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wytrzymałość.
        /// </summary>
        internal static string Durability {
            get {
                return ResourceManager.GetString("Durability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdzenie adresu e-mail.
        /// </summary>
        internal static string EmailConfirmationTitle {
            get {
                return ResourceManager.GetString("EmailConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres e-mail potwierdzony pomyślnie!.
        /// </summary>
        internal static string EmailConfirmedSuccessfully {
            get {
                return ResourceManager.GetString("EmailConfirmedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź kod pracy.
        /// </summary>
        internal static string EnterWorkCode {
            get {
                return ResourceManager.GetString("EnterWorkCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd ładowania profilu.
        /// </summary>
        internal static string ErrorLoadingProfile {
            get {
                return ResourceManager.GetString("ErrorLoadingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szacowany czas suszenia.
        /// </summary>
        internal static string EstimatedDryingTimeLabel {
            get {
                return ResourceManager.GetString("EstimatedDryingTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się potwierdzić adresu e-mail..
        /// </summary>
        internal static string FailedToConfirmEmail {
            get {
                return ResourceManager.GetString("FailedToConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieudane ładowanie prac: {0}.
        /// </summary>
        internal static string FailedToLoadWorks {
            get {
                return ResourceManager.GetString("FailedToLoadWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtruj według typu.
        /// </summary>
        internal static string FilterByType {
            get {
                return ResourceManager.GetString("FilterByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie odciskiem palca.
        /// </summary>
        internal static string FingerPrintLogin {
            get {
                return ResourceManager.GetString("FingerPrintLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwierzytelnianie biometryczne nie powiodło się.
        /// </summary>
        internal static string FingerPrintLoginFailed {
            get {
                return ResourceManager.GetString("FingerPrintLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użyj odcisku palca, aby się zalogować.
        /// </summary>
        internal static string FingerPrintLoginMsg {
            get {
                return ResourceManager.GetString("FingerPrintLoginMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykończenie.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametry wypalania.
        /// </summary>
        internal static string FiringParameters {
            get {
                return ResourceManager.GetString("FiringParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametry wypalania wkrótce.
        /// </summary>
        internal static string FiringParametersComingSoon {
            get {
                return ResourceManager.GetString("FiringParametersComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezpieczne dla żywności.
        /// </summary>
        internal static string FoodSafeLabel {
            get {
                return ResourceManager.GetString("FoodSafeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezpieczeństwo żywności.
        /// </summary>
        internal static string FoodSafety {
            get {
                return ResourceManager.GetString("FoodSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma.
        /// </summary>
        internal static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcjonalna.
        /// </summary>
        internal static string Functional {
            get {
                return ResourceManager.GetString("Functional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd..
        /// </summary>
        internal static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zachowanie glazury.
        /// </summary>
        internal static string GlazeBehavior {
            get {
                return ResourceManager.GetString("GlazeBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detale szkliwa.
        /// </summary>
        internal static string GlazeDetails {
            get {
                return ResourceManager.GetString("GlazeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa szkliwa.
        /// </summary>
        internal static string GlazeName {
            get {
                return ResourceManager.GetString("GlazeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa glazury jest wymagana..
        /// </summary>
        internal static string GlazeNameRequired {
            get {
                return ResourceManager.GetString("GlazeNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ szkliwa.
        /// </summary>
        internal static string GlazeType {
            get {
                return ResourceManager.GetString("GlazeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błyszczące.
        /// </summary>
        internal static string Gloss {
            get {
                return ResourceManager.GetString("Gloss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wróć.
        /// </summary>
        internal static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przejdź do logowania.
        /// </summary>
        internal static string GoToLogin {
            get {
                return ResourceManager.GetString("GoToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysoka.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysoko reaktywna.
        /// </summary>
        internal static string HighlyReactive {
            get {
                return ResourceManager.GetString("HighlyReactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicjały.
        /// </summary>
        internal static string Initials {
            get {
                return ResourceManager.GetString("Initials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowy link potwierdzający..
        /// </summary>
        internal static string InvalidConfirmationLink {
            get {
                return ResourceManager.GetString("InvalidConfirmationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowa operacja..
        /// </summary>
        internal static string InvalidOperation {
            get {
                return ResourceManager.GetString("InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baza wiedzy.
        /// </summary>
        internal static string KnowledgeBase {
            get {
                return ResourceManager.GetString("KnowledgeBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znane problemy i jak je zapobiegać....
        /// </summary>
        internal static string KnownIssues {
            get {
                return ResourceManager.GetString("KnownIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Płynna.
        /// </summary>
        internal static string Liquid {
            get {
                return ResourceManager.GetString("Liquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd logowania.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj użytkownika.
        /// </summary>
        internal static string LoginHint {
            get {
                return ResourceManager.GetString("LoginHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się odciskiem palca.
        /// </summary>
        internal static string LoginWithFingerprint {
            get {
                return ResourceManager.GetString("LoginWithFingerprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz się wylogować?.
        /// </summary>
        internal static string LogoutConfirmationMessage {
            get {
                return ResourceManager.GetString("LogoutConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wylogowanie.
        /// </summary>
        internal static string LogoutConfirmationTitle {
            get {
                return ResourceManager.GetString("LogoutConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niska.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producent.
        /// </summary>
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oznacz jako ulubione.
        /// </summary>
        internal static string MarkAsFavorite {
            get {
                return ResourceManager.GetString("MarkAsFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matowe.
        /// </summary>
        internal static string Matte {
            get {
                return ResourceManager.GetString("Matte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Płynność topnienia.
        /// </summary>
        internal static string MeltFluidity {
            get {
                return ResourceManager.GetString("MeltFluidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~25 mm.
        /// </summary>
        internal static string MidWallLabel {
            get {
                return ResourceManager.GetString("MidWallLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notatki łagodzące.
        /// </summary>
        internal static string MitigationNotes {
            get {
                return ResourceManager.GetString("MitigationNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje prace.
        /// </summary>
        internal static string MyWorks {
            get {
                return ResourceManager.GetString("MyWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd sieci. Sprawdź połączenie..
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutralna.
        /// </summary>
        internal static string Neutral {
            get {
                return ResourceManager.GetString("Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa praca.
        /// </summary>
        internal static string NewWorkPage {
            get {
                return ResourceManager.GetString("NewWorkPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie masz konta?.
        /// </summary>
        internal static string NoAccount {
            get {
                return ResourceManager.GetString("NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie otrzymano linku potwierdzającego..
        /// </summary>
        internal static string NoConfirmationLinkReceived {
            get {
                return ResourceManager.GetString("NoConfirmationLinkReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak zapisanych danych logowania dla logowania odciskiem palca.
        /// </summary>
        internal static string NoFingerPrintDataSaved {
            get {
                return ResourceManager.GetString("NoFingerPrintDataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono glazur. Dodaj swoją pierwszą glazurę!.
        /// </summary>
        internal static string NoGlazesFound {
            get {
                return ResourceManager.GetString("NoGlazesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono materiałów..
        /// </summary>
        internal static string NoMaterialsFound {
            get {
                return ResourceManager.GetString("NoMaterialsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak zdjęcia.
        /// </summary>
        internal static string NoPhoto {
            get {
                return ResourceManager.GetString("NoPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wybrano zdjęcia.
        /// </summary>
        internal static string NoPhotoSelected {
            get {
                return ResourceManager.GetString("NoPhotoSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notatki.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niebezpieczne.
        /// </summary>
        internal static string NotSafe {
            get {
                return ResourceManager.GetString("NotSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak informacji.
        /// </summary>
        internal static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie testowane.
        /// </summary>
        internal static string NotTested {
            get {
                return ResourceManager.GetString("NotTested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak prac.
        /// </summary>
        internal static string NoWorksYet {
            get {
                return ResourceManager.GetString("NoWorksYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak internetu.
        /// </summary>
        internal static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kryjące.
        /// </summary>
        internal static string Opaque {
            get {
                return ResourceManager.GetString("Opaque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcjonalne szczegóły.
        /// </summary>
        internal static string OptionalDetails {
            get {
                return ResourceManager.GetString("OptionalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oksydacja.
        /// </summary>
        internal static string Oxidation {
            get {
                return ResourceManager.GetString("Oxidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysyłka danych do bazy....
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdjęcia.
        /// </summary>
        internal static string PhotoTitle {
            get {
                return ResourceManager.GetString("PhotoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz zdjęcie.
        /// </summary>
        internal static string PickPhoto {
            get {
                return ResourceManager.GetString("PickPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        internal static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość (np. 500g, pół słoika).
        /// </summary>
        internal static string QuantityExample {
            get {
                return ResourceManager.GetString("QuantityExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość.
        /// </summary>
        internal static string QuantityLabel {
            get {
                return ResourceManager.GetString("QuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana grubość (np. 2-3 mm).
        /// </summary>
        internal static string RecommendedThicknessExample {
            get {
                return ResourceManager.GetString("RecommendedThicknessExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redukcja.
        /// </summary>
        internal static string Reduction {
            get {
                return ResourceManager.GetString("Reduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powtarzalność.
        /// </summary>
        internal static string Repeatability {
            get {
                return ResourceManager.GetString("Repeatability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przekroczono limit czasu żądania. Spróbuj ponownie..
        /// </summary>
        internal static string RequestTimeout {
            get {
                return ResourceManager.GetString("RequestTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymagane informacje.
        /// </summary>
        internal static string RequiredInformation {
            get {
                return ResourceManager.GetString("RequiredInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zasób nie znaleziony..
        /// </summary>
        internal static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezpieczne.
        /// </summary>
        internal static string Safe {
            get {
                return ResourceManager.GetString("Safe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satynowe.
        /// </summary>
        internal static string Satin {
            get {
                return ResourceManager.GetString("Satin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj glazur....
        /// </summary>
        internal static string SearchGlazesPlaceholder {
            get {
                return ResourceManager.GetString("SearchGlazesPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj materiałów....
        /// </summary>
        internal static string SearchWikiPlaceholder {
            get {
                return ResourceManager.GetString("SearchWikiPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz kategorię.
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę wybrać kategorię.
        /// </summary>
        internal static string SelectCategoryValidation {
            get {
                return ResourceManager.GetString("SelectCategoryValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz wytrzymałość.
        /// </summary>
        internal static string SelectDurability {
            get {
                return ResourceManager.GetString("SelectDurability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz typ interakcji.
        /// </summary>
        internal static string SelectInteractionType {
            get {
                return ResourceManager.GetString("SelectInteractionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz status.
        /// </summary>
        internal static string SelectStatus {
            get {
                return ResourceManager.GetString("SelectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz typ pracy.
        /// </summary>
        internal static string SelectWorkType {
            get {
                return ResourceManager.GetString("SelectWorkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Półmatowe.
        /// </summary>
        internal static string SemiMatte {
            get {
                return ResourceManager.GetString("SemiMatte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Półprzejrzyste.
        /// </summary>
        internal static string SemiTransparent {
            get {
                return ResourceManager.GetString("SemiTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj się.
        /// </summary>
        internal static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd podczas rejestracji.
        /// </summary>
        internal static string SignUpError {
            get {
                return ResourceManager.GetString("SignUpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tworzy nowe konto użytkownika.
        /// </summary>
        internal static string SignUpHint {
            get {
                return ResourceManager.GetString("SignUpHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja.
        /// </summary>
        internal static string SignupTitle {
            get {
                return ResourceManager.GetString("SignupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specjalne instrukcje....
        /// </summary>
        internal static string SpecialInstructions {
            get {
                return ResourceManager.GetString("SpecialInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stabilna.
        /// </summary>
        internal static string Stable {
            get {
                return ResourceManager.GetString("Stable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpocznij przez dodanie pracy.
        /// </summary>
        internal static string StartByAddingWork {
            get {
                return ResourceManager.GetString("StartByAddingWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sukces.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane offline wysłane.
        /// </summary>
        internal static string Synced {
            get {
                return ResourceManager.GetString("Synced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd wysyłki danych.
        /// </summary>
        internal static string SyncError {
            get {
                return ResourceManager.GetString("SyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysyłam dane.....
        /// </summary>
        internal static string Syncing {
            get {
                return ResourceManager.GetString("Syncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status synchronizacji.
        /// </summary>
        internal static string SyncStatus {
            get {
                return ResourceManager.GetString("SyncStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd synchronizacji.
        /// </summary>
        internal static string SyncStatusError {
            get {
                return ResourceManager.GetString("SyncStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oczekujące.
        /// </summary>
        internal static string SyncStatusPending {
            get {
                return ResourceManager.GetString("SyncStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zsynchronizowane.
        /// </summary>
        internal static string SyncStatusSynced {
            get {
                return ResourceManager.GetString("SyncStatusSynced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizowanie.
        /// </summary>
        internal static string SyncStatusSyncing {
            get {
                return ResourceManager.GetString("SyncStatusSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieznany.
        /// </summary>
        internal static string SyncStatusUnknown {
            get {
                return ResourceManager.GetString("SyncStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaawansowane.
        /// </summary>
        internal static string TabAdvanced {
            get {
                return ResourceManager.GetString("TabAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analizy.
        /// </summary>
        internal static string TabAnalyticsTitle {
            get {
                return ResourceManager.GetString("TabAnalyticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygląd.
        /// </summary>
        internal static string TabAppearance {
            get {
                return ResourceManager.GetString("TabAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikacja.
        /// </summary>
        internal static string TabApplication {
            get {
                return ResourceManager.GetString("TabApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podstawowe.
        /// </summary>
        internal static string TabBasic {
            get {
                return ResourceManager.GetString("TabBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zachowanie.
        /// </summary>
        internal static string TabBehavior {
            get {
                return ResourceManager.GetString("TabBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wypalanie.
        /// </summary>
        internal static string TabFiring {
            get {
                return ResourceManager.GetString("TabFiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inwentarz.
        /// </summary>
        internal static string TabInventoryTitle {
            get {
                return ResourceManager.GetString("TabInventoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        internal static string TabProfileTitle {
            get {
                return ResourceManager.GetString("TabProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wikipedia.
        /// </summary>
        internal static string TabWikiTitle {
            get {
                return ResourceManager.GetString("TabWikiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prace.
        /// </summary>
        internal static string TabWorksTitle {
            get {
                return ResourceManager.GetString("TabWorksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrób zdjęcie.
        /// </summary>
        internal static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakres temperatury.
        /// </summary>
        internal static string TemperatureRange {
            get {
                return ResourceManager.GetString("TemperatureRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerancja grubości.
        /// </summary>
        internal static string ThicknessTolerance {
            get {
                return ResourceManager.GetString("ThicknessTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 mm (gruba).
        /// </summary>
        internal static string ThickWallLabel {
            get {
                return ResourceManager.GetString("ThickWallLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 mm (cienka).
        /// </summary>
        internal static string ThinWallLabel {
            get {
                return ResourceManager.GetString("ThinWallLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozostało: {0:d\d\ h\h\ m\m}.
        /// </summary>
        internal static string TimeLeft {
            get {
                return ResourceManager.GetString("TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przejrzystość.
        /// </summary>
        internal static string Transparency {
            get {
                return ResourceManager.GetString("Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przejrzyste.
        /// </summary>
        internal static string Transparent {
            get {
                return ResourceManager.GetString("Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        internal static string TypeLabel {
            get {
                return ResourceManager.GetString("TypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak dostępu. Zaloguj się ponownie..
        /// </summary>
        internal static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednostka.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmieniono.
        /// </summary>
        internal static string UpdatedAt {
            get {
                return ResourceManager.GetString("UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik niezalogowany.
        /// </summary>
        internal static string UserNotLoggedIn {
            get {
                return ResourceManager.GetString("UserNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono profilu.
        /// </summary>
        internal static string UserProfileNotFound {
            get {
                return ResourceManager.GetString("UserProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdzanie.
        /// </summary>
        internal static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmienna.
        /// </summary>
        internal static string Variable {
            get {
                return ResourceManager.GetString("Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wersja.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grubość ścianki.
        /// </summary>
        internal static string WallThickness {
            get {
                return ResourceManager.GetString("WallThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grubość ścianki.
        /// </summary>
        internal static string WallThicknessTitle {
            get {
                return ResourceManager.GetString("WallThicknessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowa grubość ścianki.
        /// </summary>
        internal static string WallThicknessValidation {
            get {
                return ResourceManager.GetString("WallThicknessValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witamy ponownie!.
        /// </summary>
        internal static string WelcomeBack {
            get {
                return ResourceManager.GetString("WelcomeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeglądaj informacje zweryfikowane przez społeczność na temat materiałów ceramicznych, narzędzi i technik..
        /// </summary>
        internal static string WikiDescription {
            get {
                return ResourceManager.GetString("WikiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miska.
        /// </summary>
        internal static string WorkCategory_BOWL {
            get {
                return ResourceManager.GetString("WorkCategory_BOWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kubek.
        /// </summary>
        internal static string WorkCategory_CUP {
            get {
                return ResourceManager.GetString("WorkCategory_CUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inne.
        /// </summary>
        internal static string WorkCategory_OTHER {
            get {
                return ResourceManager.GetString("WorkCategory_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talerz.
        /// </summary>
        internal static string WorkCategory_PLATE {
            get {
                return ResourceManager.GetString("WorkCategory_PLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rzeźba.
        /// </summary>
        internal static string WorkCategory_SCULPTURE {
            get {
                return ResourceManager.GetString("WorkCategory_SCULPTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Płytka.
        /// </summary>
        internal static string WorkCategory_TILE {
            get {
                return ResourceManager.GetString("WorkCategory_TILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wazon.
        /// </summary>
        internal static string WorkCategory_VASE {
            get {
                return ResourceManager.GetString("WorkCategory_VASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod pracy.
        /// </summary>
        internal static string WorkCode {
            get {
                return ResourceManager.GetString("WorkCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowy kod pracy lub długość kodu..
        /// </summary>
        internal static string WorkCodeValidation {
            get {
                return ResourceManager.GetString("WorkCodeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praca utworzona z kodem: {0}.
        /// </summary>
        internal static string WorkCreated {
            get {
                return ResourceManager.GetString("WorkCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się utworzyć pracy: {0}.
        /// </summary>
        internal static string WorkCreationFailed {
            get {
                return ResourceManager.GetString("WorkCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detale pracy.
        /// </summary>
        internal static string WorkDetails {
            get {
                return ResourceManager.GetString("WorkDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biszkwit.
        /// </summary>
        internal static string WorkStatus_BISQUE_FIRED {
            get {
                return ResourceManager.GetString("WorkStatus_BISQUE_FIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koścista sucha.
        /// </summary>
        internal static string WorkStatus_BONE_DRY {
            get {
                return ResourceManager.GetString("WorkStatus_BONE_DRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukończona.
        /// </summary>
        internal static string WorkStatus_COMPLETED {
            get {
                return ResourceManager.GetString("WorkStatus_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odrzucona.
        /// </summary>
        internal static string WorkStatus_DISCARDED {
            get {
                return ResourceManager.GetString("WorkStatus_DISCARDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wypalona z glazurą.
        /// </summary>
        internal static string WorkStatus_GLAZE_FIRED {
            get {
                return ResourceManager.GetString("WorkStatus_GLAZE_FIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glazurowana.
        /// </summary>
        internal static string WorkStatus_GLAZED {
            get {
                return ResourceManager.GetString("WorkStatus_GLAZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skórzasta.
        /// </summary>
        internal static string WorkStatus_LEATHER_HARD {
            get {
                return ResourceManager.GetString("WorkStatus_LEATHER_HARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mokra.
        /// </summary>
        internal static string WorkStatus_WET {
            get {
                return ResourceManager.GetString("WorkStatus_WET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ pracy.
        /// </summary>
        internal static string WorkType {
            get {
                return ResourceManager.GetString("WorkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 dni.
        /// </summary>
        internal static string ZeroDays {
            get {
                return ResourceManager.GetString("ZeroDays", resourceCulture);
            }
        }
    }
}
