//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PottMaster.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PottMaster.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikacji.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto utworzone, możesz się zalogować..
        /// </summary>
        internal static string AccountCreatedPleaseLogin {
            get {
                return ResourceManager.GetString("AccountCreatedPleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia konta.
        /// </summary>
        internal static string AccountSettings {
            get {
                return ResourceManager.GetString("AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nową pracę.
        /// </summary>
        internal static string AddNewWork {
            get {
                return ResourceManager.GetString("AddNewWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masz już konto? Zaloguj się.
        /// </summary>
        internal static string AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PottMaster.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria.
        /// </summary>
        internal static string CategoryTitle {
            get {
                return ResourceManager.GetString("CategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień status.
        /// </summary>
        internal static string ChangeStatus {
            get {
                return ResourceManager.GetString("ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana statusu.
        /// </summary>
        internal static string ChangeStatusTitle {
            get {
                return ResourceManager.GetString("ChangeStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy potwierdzasz zmianę statusu?.
        /// </summary>
        internal static string ConfirmChangeStatusMessage {
            get {
                return ResourceManager.GetString("ConfirmChangeStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz usunąć pracę?.
        /// </summary>
        internal static string ConfirmDeleteWorkMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteWorkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź usunięcie.
        /// </summary>
        internal static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz usunąć?.
        /// </summary>
        internal static string ConfirmDeletionMessage {
            get {
                return ResourceManager.GetString("ConfirmDeletionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz nowe konto.
        /// </summary>
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utworzono.
        /// </summary>
        internal static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz pracę.
        /// </summary>
        internal static string CreateWork {
            get {
                return ResourceManager.GetString("CreateWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tworzenie....
        /// </summary>
        internal static string CreatingWork {
            get {
                return ResourceManager.GetString("CreatingWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strefa zagro?enia.
        /// </summary>
        internal static string DangerZone {
            get {
                return ResourceManager.GetString("DangerZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuwanie.
        /// </summary>
        internal static string DeleteWorkTitle {
            get {
                return ResourceManager.GetString("DeleteWorkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suszenie zakończone.
        /// </summary>
        internal static string DryingCompleted {
            get {
                return ResourceManager.GetString("DryingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakonczono: {0:d\d\ h\h\ m\m}.
        /// </summary>
        internal static string DryingCompletedAtFormat {
            get {
                return ResourceManager.GetString("DryingCompletedAtFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suszenie zakończone!.
        /// </summary>
        internal static string DryingCompleteInfo {
            get {
                return ResourceManager.GetString("DryingCompleteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praca {0} wyschła i jest gotowa na następny etap.
        /// </summary>
        internal static string DryingCompleteMessage {
            get {
                return ResourceManager.GetString("DryingCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dni.
        /// </summary>
        internal static string DryingDays {
            get {
                return ResourceManager.GetString("DryingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpoczęto: {0:d\d\ h\h\ m\m}.
        /// </summary>
        internal static string DryingStartedFormat {
            get {
                return ResourceManager.GetString("DryingStartedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas suszenia.
        /// </summary>
        internal static string DryingTime {
            get {
                return ResourceManager.GetString("DryingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź kod pracy.
        /// </summary>
        internal static string EnterWorkCode {
            get {
                return ResourceManager.GetString("EnterWorkCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd ładowania profilu.
        /// </summary>
        internal static string ErrorLoadingProfile {
            get {
                return ResourceManager.GetString("ErrorLoadingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szacowany czas suszenia.
        /// </summary>
        internal static string EstimatedDryingTimeLabel {
            get {
                return ResourceManager.GetString("EstimatedDryingTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieudane ładowanie prac: {0}.
        /// </summary>
        internal static string FailedToLoadWorks {
            get {
                return ResourceManager.GetString("FailedToLoadWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wróć.
        /// </summary>
        internal static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicjały.
        /// </summary>
        internal static string Initials {
            get {
                return ResourceManager.GetString("Initials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd logowania.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj użytkownika.
        /// </summary>
        internal static string LoginHint {
            get {
                return ResourceManager.GetString("LoginHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz się wylogować?.
        /// </summary>
        internal static string LogoutConfirmationMessage {
            get {
                return ResourceManager.GetString("LogoutConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wylogowanie.
        /// </summary>
        internal static string LogoutConfirmationTitle {
            get {
                return ResourceManager.GetString("LogoutConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~25 mm.
        /// </summary>
        internal static string MidWallLabel {
            get {
                return ResourceManager.GetString("MidWallLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje prace.
        /// </summary>
        internal static string MyWorks {
            get {
                return ResourceManager.GetString("MyWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa praca.
        /// </summary>
        internal static string NewWorkPage {
            get {
                return ResourceManager.GetString("NewWorkPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie masz konta?.
        /// </summary>
        internal static string NoAccount {
            get {
                return ResourceManager.GetString("NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak zdjęcia.
        /// </summary>
        internal static string NoPhoto {
            get {
                return ResourceManager.GetString("NoPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wybrano zdjęcia.
        /// </summary>
        internal static string NoPhotoSelected {
            get {
                return ResourceManager.GetString("NoPhotoSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak prac.
        /// </summary>
        internal static string NoWorksYet {
            get {
                return ResourceManager.GetString("NoWorksYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdjęcia.
        /// </summary>
        internal static string PhotoTitle {
            get {
                return ResourceManager.GetString("PhotoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz zdjęcie.
        /// </summary>
        internal static string PickPhoto {
            get {
                return ResourceManager.GetString("PickPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        internal static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz kategorię.
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę wybrać kategorię.
        /// </summary>
        internal static string SelectCategoryValidation {
            get {
                return ResourceManager.GetString("SelectCategoryValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj się.
        /// </summary>
        internal static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd podczas rejestracji.
        /// </summary>
        internal static string SignUpError {
            get {
                return ResourceManager.GetString("SignUpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tworzy nowe konto użytkownika.
        /// </summary>
        internal static string SignUpHint {
            get {
                return ResourceManager.GetString("SignUpHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja.
        /// </summary>
        internal static string SignupTitle {
            get {
                return ResourceManager.GetString("SignupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpocznij przez dodanie pracy.
        /// </summary>
        internal static string StartByAddingWork {
            get {
                return ResourceManager.GetString("StartByAddingWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sukces.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status synchronizacji.
        /// </summary>
        internal static string SyncStatus {
            get {
                return ResourceManager.GetString("SyncStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd synchronizacji.
        /// </summary>
        internal static string SyncStatusError {
            get {
                return ResourceManager.GetString("SyncStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oczekujące.
        /// </summary>
        internal static string SyncStatusPending {
            get {
                return ResourceManager.GetString("SyncStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zsynchronizowane.
        /// </summary>
        internal static string SyncStatusSynced {
            get {
                return ResourceManager.GetString("SyncStatusSynced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizowanie.
        /// </summary>
        internal static string SyncStatusSyncing {
            get {
                return ResourceManager.GetString("SyncStatusSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieznany.
        /// </summary>
        internal static string SyncStatusUnknown {
            get {
                return ResourceManager.GetString("SyncStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analizy.
        /// </summary>
        internal static string TabAnalyticsTitle {
            get {
                return ResourceManager.GetString("TabAnalyticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inwentarz.
        /// </summary>
        internal static string TabInventoryTitle {
            get {
                return ResourceManager.GetString("TabInventoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        internal static string TabProfileTitle {
            get {
                return ResourceManager.GetString("TabProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wikipedia.
        /// </summary>
        internal static string TabWikiTitle {
            get {
                return ResourceManager.GetString("TabWikiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prace.
        /// </summary>
        internal static string TabWorksTitle {
            get {
                return ResourceManager.GetString("TabWorksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrób zdjęcie.
        /// </summary>
        internal static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 mm (gruba).
        /// </summary>
        internal static string ThickWallLabel {
            get {
                return ResourceManager.GetString("ThickWallLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 mm (cienka).
        /// </summary>
        internal static string ThinWallLabel {
            get {
                return ResourceManager.GetString("ThinWallLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozostało: {0:d\d\ h\h\ m\m}.
        /// </summary>
        internal static string TimeLeft {
            get {
                return ResourceManager.GetString("TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmieniono.
        /// </summary>
        internal static string UpdatedAt {
            get {
                return ResourceManager.GetString("UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik niezalogowany.
        /// </summary>
        internal static string UserNotLoggedIn {
            get {
                return ResourceManager.GetString("UserNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono profilu.
        /// </summary>
        internal static string UserProfileNotFound {
            get {
                return ResourceManager.GetString("UserProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdzanie.
        /// </summary>
        internal static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wersja.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grubość ścianki.
        /// </summary>
        internal static string WallThickness {
            get {
                return ResourceManager.GetString("WallThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grubość ścianki.
        /// </summary>
        internal static string WallThicknessTitle {
            get {
                return ResourceManager.GetString("WallThicknessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowa grubość ścianki.
        /// </summary>
        internal static string WallThicknessValidation {
            get {
                return ResourceManager.GetString("WallThicknessValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witamy ponownie!.
        /// </summary>
        internal static string WelcomeBack {
            get {
                return ResourceManager.GetString("WelcomeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miska.
        /// </summary>
        internal static string WorkCategory_BOWL {
            get {
                return ResourceManager.GetString("WorkCategory_BOWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kubek.
        /// </summary>
        internal static string WorkCategory_CUP {
            get {
                return ResourceManager.GetString("WorkCategory_CUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inne.
        /// </summary>
        internal static string WorkCategory_OTHER {
            get {
                return ResourceManager.GetString("WorkCategory_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talerz.
        /// </summary>
        internal static string WorkCategory_PLATE {
            get {
                return ResourceManager.GetString("WorkCategory_PLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rzeźba.
        /// </summary>
        internal static string WorkCategory_SCULPTURE {
            get {
                return ResourceManager.GetString("WorkCategory_SCULPTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Płytka.
        /// </summary>
        internal static string WorkCategory_TILE {
            get {
                return ResourceManager.GetString("WorkCategory_TILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wazon.
        /// </summary>
        internal static string WorkCategory_VASE {
            get {
                return ResourceManager.GetString("WorkCategory_VASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod pracy.
        /// </summary>
        internal static string WorkCode {
            get {
                return ResourceManager.GetString("WorkCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praca utworzona z kodem: {0}.
        /// </summary>
        internal static string WorkCreated {
            get {
                return ResourceManager.GetString("WorkCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się utworzyć pracy: {0}.
        /// </summary>
        internal static string WorkCreationFailed {
            get {
                return ResourceManager.GetString("WorkCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detale pracy.
        /// </summary>
        internal static string WorkDetails {
            get {
                return ResourceManager.GetString("WorkDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biszkwit.
        /// </summary>
        internal static string WorkStatus_BISQUE_FIRED {
            get {
                return ResourceManager.GetString("WorkStatus_BISQUE_FIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koścista sucha.
        /// </summary>
        internal static string WorkStatus_BONE_DRY {
            get {
                return ResourceManager.GetString("WorkStatus_BONE_DRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukończona.
        /// </summary>
        internal static string WorkStatus_COMPLETED {
            get {
                return ResourceManager.GetString("WorkStatus_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odrzucona.
        /// </summary>
        internal static string WorkStatus_DISCARDED {
            get {
                return ResourceManager.GetString("WorkStatus_DISCARDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wypalona z glazurą.
        /// </summary>
        internal static string WorkStatus_GLAZE_FIRED {
            get {
                return ResourceManager.GetString("WorkStatus_GLAZE_FIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glazurowana.
        /// </summary>
        internal static string WorkStatus_GLAZED {
            get {
                return ResourceManager.GetString("WorkStatus_GLAZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skórzasta.
        /// </summary>
        internal static string WorkStatus_LEATHER_HARD {
            get {
                return ResourceManager.GetString("WorkStatus_LEATHER_HARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mokra.
        /// </summary>
        internal static string WorkStatus_WET {
            get {
                return ResourceManager.GetString("WorkStatus_WET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
